[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "moge"
description = "MoGe: Unlocking Accurate Monocular Geometry Estimation for Open-Domain Images with Optimal Training Supervision"
version = "0.1"
dependencies = [
    'numpy<2.0',
    'click==8.1',
    'torch==2.2',
    'torchvision==0.15',
    'opencv-python==4.11',
    'scipy==1.11',
    'trimesh==4.6',
    'matplotlib==3.8',
    'pillow==10.3',
    'huggingface_hub==0.29',
    'sympy==1.13',
    'filelock==3.0',
]

[tool.setuptools.packages]
find = {}

